env:
 global:
   - CC_TEST_REPORTER_ID=bc8bfe4e40c3544a3c87948476c8541333cc39f1e080e08f558ac798ed662c8f
language: node_js
node_js:
 - "8"
script: npm run test
before_script:
 - npm install
 - npm install jasmine -g
 - npm run-script build
 - npm start
after_script:
 
after_success:
 - npm run coverage
 - npm run report-coverage
